In [1]:
import duckdb
import pandas as pd

In [5]:
## ---- check tables ----
# Connect to your local database
database_path = "data/warehouse/transitionwatch.duckdb"

with duckdb.connect(database=database_path, read_only=True) as con:
    # SHOW ALL TABLES returns the database, schema, name, and column names
    catalog_df = con.execute("SHOW ALL TABLES").fetchdf()

# Display the results
catalog_df[['name', 'column_names']]

,name,column_names
0,stg_ember__carbon_intensity,"[carbon_intensity_id, entity, entity_code, mon..."
1,stg_ember__demand,"[demand_id, entity, entity_code, month_date, d..."
2,stg_ember__generation,"[generation_id, entity, entity_code, series, m..."
3,stg_ember__installed_capacity,"[installed_capacity_id, entity, entity_code, s..."
4,stg_ember__power_sector_emission,"[power_sector_emission_id, entity, entity_code..."

In [6]:
df = pd.DataFrame()

with duckdb.connect(database=database_path, read_only=True) as con:
    df = con.execute("SELECT * FROM main_staging.stg_ember__generation LIMIT 100").fetchdf()

df.sample(5)

,generation_id,entity,entity_code,series,month_date,generation_twh,share_of_generation_pct,is_aggregate_entity,is_aggregate_series,extracted_at,logical_date
95,0a5cc7682db5fa20af2eb67435e260c7,Finland,FIN,Other fossil,2025-12-01,0.33,4.08,False,False,2026-05-08 21:47:28.922769,2026-04-01
78,505ffa4e899570fd6c49150f83c5c834,Ecuador,ECU,Bioenergy,2026-01-01,0.01,0.32,False,False,2026-05-08 21:47:28.934592,2026-04-01
11,8ed255391e25155d3263c21dee756011,Austria,AUT,Other fossil,2025-10-01,0.09,1.64,False,False,2026-05-08 21:47:28.896992,2026-04-01
66,b39a8b5a9a2a110887d44d8c68e66639,Czechia,CZE,Nuclear,2025-10-01,2.61,44.77,False,False,2026-05-08 21:47:28.896992,2026-04-01
69,91b3c770ee45e53d8a9b3ca0b8afe233,Czechia,CZE,Other renewables,2026-03-01,0.20,3.13,False,False,2026-05-08 21:47:28.961630,2026-04-01

In [ ]:
# # --- view the schema of a table ---
# with duckdb.connect(database=database_path, read_only=True) as con:
#     # Let's inspect the Gold layer table you just built
#     schema_df = con.execute("DESCRIBE tableName").fetchdf()
# schema_df

CatalogException: Catalog Error: Table with name stg_ember__generation does not exist!
Did you mean "main_staging.stg_ember__generation"?

LINE 1: DESCRIBE stg_ember__generation
                 ^